apiVersion: v1
kind: Pod
metadata:
  name: alpine-demo
  namespace: falco-demo
spec:
  containers:
  - name: alpine
    image: alpine:3.20
    command: ["sh","-c","sleep 3600"]
    securityContext:
      runAsUser: 0
      allowPrivilegeEscalation: false